# print("Day 1 - python print function")
# print("The function is declared like this:")
# print("print('what to print')")
# print('print("what to print")')
# print("Hello World!")
# print("Hello World!")
# print("Hello World!")
# print("Hello World! /n Hello World! /n Hello World!")
# print("Hello World!/n Hello World!/n Hello World!")
# print("Hello World!\nHello World!\nHello World!")
print("Hello" + " " + "Ali")
print("print('Ali')")